'use client';

import { useState, useEffect } from 'react';
import Editor from '@monaco-editor/react';
import { Loader2 } from 'lucide-react';

interface CodeEditorProps {
  file: string | null;
  projectId: string;
}

// Mock file contents - in production, this would be fetched from the API
const mockFileContents: Record<string, string> = {
  'src/app/page.tsx': `import { Button } from '@/components/ui/button';

export default function HomePage() {
  return (
    <main className="min-h-screen flex items-center justify-center">
      <div className="text-center space-y-6">
        <h1 className="text-4xl font-bold">
          Welcome to Your App
        </h1>
        <p className="text-muted-foreground">
          Built with AI
        </p>
        <Button>Get Started</Button>
      </div>
    </main>
  );
}
`,
  'src/app/layout.tsx': `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by AI',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
  'package.json': `{
  "name": "my-saas-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.0.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
`,
};

export function CodeEditor({ file, projectId }: CodeEditorProps) {
  const [content, setContent] = useState<string>('');
  const [language, setLanguage] = useState<string>('typescript');

  useEffect(() => {
    if (file) {
      // In production, fetch file content from API
      const fileContent = mockFileContents[file] || `// ${file}`;
      setContent(fileContent);

      // Determine language from file extension
      const ext = file.split('.').pop();
      const langMap: Record<string, string> = {
        tsx: 'typescript',
        ts: 'typescript',
        jsx: 'javascript',
        js: 'javascript',
        json: 'json',
        css: 'css',
        md: 'markdown',
      };
      setLanguage(langMap[ext || 'txt'] || 'plaintext');
    }
  }, [file]);

  const handleEditorChange = (value: string | undefined) => {
    if (value !== undefined) {
      setContent(value);
      // TODO: Debounce and save to backend
    }
  };

  if (!file) {
    return (
      <div className="flex-1 flex items-center justify-center text-muted-foreground">
        Select a file to edit
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col">
      {/* File Tab */}
      <div className="h-10 border-b flex items-center px-4 bg-muted/20">
        <span className="text-sm font-medium">{file}</span>
      </div>

      {/* Editor */}
      <div className="flex-1">
        <Editor
          height="100%"
          language={language}
          value={content}
          onChange={handleEditorChange}
          theme="vs-dark"
          options={{
            minimap: { enabled: false },
            fontSize: 14,
            lineNumbers: 'on',
            rulers: [],
            wordWrap: 'on',
            tabSize: 2,
            automaticLayout: true,
          }}
          loading={
            <div className="h-full flex items-center justify-center">
              <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
            </div>
          }
        />
      </div>
    </div>
  );
}
